### ISSUE TITLE
SelenideAddons.wrapAssertionError

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#99]
If the wrapped assertion error does not contain a messagethe output contains a missleading "null".

e.g. "UIAssertionError AssertionError: null"

The functionality should better state that no error message was provided for the assertion.

**Comment by jowerner** [comment]
Looks like the replacement message is effective only when writing the log, but the thrown error still shows null:

```
UIAssertionError AssertionError: null
Screenshot: file:/D:/workspace/neodymium-template/build/reports/tests/1567080799625.0.png
Page source: file:/D:/workspace/neodymium-template/build/reports/tests/1567080799625.0.html
Timeout: 1567080799.620 s.
Caused by: java.lang.AssertionError
	at com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:58)
	at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:54)
	at com.xceptance.neodymium.util.SelenideAddons.wrapAssertionError(SelenideAddons.java:278)
	at template.pageobjects.pages.HomePage.isExpectedPage(HomePage.java:32)
	at template.neodymium.tests.smoke.HomePageTest.testVisitingHomepage(HomePageTest.java:20)
Caused by: java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at template.pageobjects.pages.HomePage.lambda$0(HomePage.java:32)
	at com.xceptance.neodymium.util.SelenideAddons.wrapAssertionError(SelenideAddons.java:265)
	... 27 more
```

**Comment by occupant23** [comment]
fixed
